name: invasive_species_finder
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  camera: ^0.10.5+5
  image_picker: ^0.8.3
  path_provider: ^2.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.14
  badges: ^2.0.3
  json_theme: ^4.0.0
  flutter_markdown: ^0.6.13
  flutter_form_builder: ">=7.7.0"
  form_builder_validators: ">=8.4.0"
  intl: ">=0.17.0"
  google_maps_flutter: ^2.0.4
  geolocator: ^8.1.4
  permission_handler: ^11.0.0
  flutter_dotenv: ^5.0.2
  flutter_riverpod: ^2.4.3
  firebase_core: ^2.22.0
  firebase_auth: ^4.13.0
  cloud_firestore: ^4.13.0
  firebase_ui_auth: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/theme/
